# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-25 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_section',
            field=models.ForeignKey(db_column='note_section_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.NoteSection'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='custom_user',
            field=models.ForeignKey(db_column='custom_user_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='api.CustomUser'),
        ),
        migrations.AlterField(
            model_name='notesection',
            name='note_book',
            field=models.ForeignKey(db_column='note_book_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_sections', to='api.NoteBook'),
        ),
        migrations.AlterField(
            model_name='subnote',
            name='note',
            field=models.ForeignKey(db_column='note_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_notes', to='api.Note'),
        ),
    ]
