# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-26 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160525_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='custom_user',
            field=models.ForeignKey(db_column='custom_user_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CustomUser'),
        ),
    ]
