# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-29 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note_custom_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nickname',
        ),
    ]
