"""refactor comment model

Revision ID: 047ee36cae07
Revises: cf6e0e41f198
Create Date: 2016-12-11 21:31:33.798097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '047ee36cae07'
down_revision = 'cf6e0e41f198'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('star_ids', postgresql.ARRAY(postgresql.UUID(as_uuid=True), dimensions=1), nullable=True))
    op.drop_column('comment', 'star')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('star', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('comment', 'star_ids')
    ### end Alembic commands ###
