"""change log

Revision ID: 6dd848df483f
Revises: e8cfbdb1f579
Create Date: 2016-11-20 14:37:32.203571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd848df483f'
down_revision = 'e8cfbdb1f579'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('section_id', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'section_id')
    ### end Alembic commands ###
