"""rename notification.content to target_desc

Revision ID: 8d45b4996405
Revises: 71458cc6c1b8
Create Date: 2016-12-08 20:15:44.779415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d45b4996405'
down_revision = '71458cc6c1b8'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('target_desc', sa.String(), nullable=True))
    op.drop_column('notification', 'content')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('notification', 'target_desc')
    ### end Alembic commands ###
