"""change log

Revision ID: d24854dcc065
Revises: fcbf0893b805
Create Date: 2016-10-27 11:56:39.555354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24854dcc065'
down_revision = 'fcbf0893b805'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    ### end Alembic commands ###
